"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RAG_CONFIG = exports.EMBEDDING_CONFIG = exports.MODEL_ROUTES = exports.CLASSIFIER_PROMPT = exports.SOCRATIC_SYSTEM_PROMPT = void 0;
var socratic_1 = require("./prompts/socratic");
Object.defineProperty(exports, "SOCRATIC_SYSTEM_PROMPT", { enumerable: true, get: function () { return socratic_1.SOCRATIC_SYSTEM_PROMPT; } });
var classifier_1 = require("./prompts/classifier");
Object.defineProperty(exports, "CLASSIFIER_PROMPT", { enumerable: true, get: function () { return classifier_1.CLASSIFIER_PROMPT; } });
var models_1 = require("./models");
Object.defineProperty(exports, "MODEL_ROUTES", { enumerable: true, get: function () { return models_1.MODEL_ROUTES; } });
Object.defineProperty(exports, "EMBEDDING_CONFIG", { enumerable: true, get: function () { return models_1.EMBEDDING_CONFIG; } });
Object.defineProperty(exports, "RAG_CONFIG", { enumerable: true, get: function () { return models_1.RAG_CONFIG; } });
